### ISSUE TITLE
Probe not recognizing that Test has been quarantined

### ISSUE THREAD

**Issue by nsreidy2** [preludeorg/libraries#211]
running the "quarantine a malicious Office document" test on Windows11 

screenshot attached: the test itself seems to get quarantined by Windows Security. However, the Probe doesn't appear to realize that happened or to send back any results to be displayed again in the browser.

![test_quarantined](https://user-images.githubusercontent.com/118935081/213012080-f86ea2dc-69c1-4080-8d2d-829460a23d74.png)

**Comment by privateducky** [comment]
@makk94 this bug is caused by this line: https://github.com/preludeorg/libraries/blob/a9b75cca43250598180debf46d3a699c455e2835/shell/probe/demo.ps1#L41

The problem is, a 100 is one of a few codes that could indicate success. If the VST runs cleanly and the test passes, it'll return 100. If the VST itself is flagged - this is also a passed test - and will return (I think) a 127, by default. 

This will be a problem in both demo.sh and demo.ps1. 

Instead of triggering off of 100, we should probably list the handful of "success" codes and check the array. I don't love that because we have to "remember" that list but because this is isolated to demo experience and the whole thing is hard coded to a single test, this seems like the easy solution to me. Open to other ideas too.

**Comment by privateducky** [comment]
@kenrick can you verify how the UI is determining success on this as well?

**Comment by kenrick** [comment]
Sure, the UI is checking the detect.activity for changes periodically. If a new item is added to the activity array for this probe the ui will update and show that last result. The Result has a status code which dictates which items in the checklist have passed or failed. Once any result comes back (regardless of the status code) the UI will update and show the re-run test button instead of the OS picker

**Comment by makk94** [comment]
Some learnings:

* $LASTEXITCODE does not take a new value when this error occurs. And the variable is never reset, so it just stays whatever the exitcode was of the last exe that was actually run
  * Possibly the VST was never run so it doesn't set a new LASTEXITCODE
  * It's also possibly this from the docs: `When a script is called directly, like ./Test.ps1, or with the call operator (&) like & ./Test.ps1, the value of $LASTEXITCODE isn't changed.` I still can't find a way to call the VST to trigger LASTEXITCODE with this error tho
* There is an $Error variable (a string) that is set when PS encounters an error - could parse that instead of solely depending on $LASTEXITCODE
  * Alternative to the $Error variable is wrapping the `& $TempFile` in a try/catch

**Comment by privateducky** [comment]
@makk94 wouldnt that impact raindrop as well?

**Comment by privateducky** [comment]
@makk94 in re-reading this, we shouldn't rely on LASTEXITCODE but instead ensure a sub process is being fired, like:
```
$p = Start-Process -FilePath <path> -ArgumentList <args> -Wait -NoNewWindow -PassThru
$p.ExitCode
```

**Comment by makk94** [comment]
> @makk94 wouldnt that impact raindrop as well?

I'd think so - haven't tested yet

> @makk94 in re-reading this, we shouldn't rely on LASTEXITCODE but instead ensure a sub process is being fired, like:
> 
> ```
> $p = Start-Process -FilePath <path> -ArgumentList <args> -Wait -NoNewWindow -PassThru
> $p.ExitCode
> ```

can do that - doesn't fix this particular bug. there's still no exit code set, likely because the process was never started, so the try/catch is still needed. Not sure if Start-Process will produce any different exit codes than the call operator (&) for VSTs that are actually run

**Comment by privateducky** [comment]
@makk94 we need start-process anyway, as we need to ensure the test is run as a child process.

**Comment by privateducky** [comment]
and using start-process, even if the process fails to start, will produce a status code (1 in that case, most likely).

**Comment by makk94** [comment]
> and using start-process, even if the process fails to start, will produce a status code (1 in that case, most likely).

I'm running this and it does not produce an exit code because the command is not run
The code:
```
 $p = Start-Process -FilePath $TempFile -Wait -NoNewWindow -PassThru
 Write-Host $p.ExitCode 
```
The output:
```
-----------------------------------------------------------------------------------------------------------
[2] Executing test

Start-Process : This command cannot be run due to the error: Operation did not complete successfully because the file
contains a virus or potentially unwanted software.
At C:\Users\Administrator\Desktop\demo.ps1:58 char:10
+     $p = Start-Process -FilePath $TempFile -Wait -NoNewWindow -PassTh ...
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCommand

[!] Result: control test failed
```

And when I force runtime errors (ex. segfault), i don't see a different in $LASTEXITCODE (run via call operator) and $p.exitcode (run via Start-Process). Obvi didn't test all the possible errors and maybe there's some out there that do make a difference ¯\_(ツ)_/¯

Being said, running as a child process makes sense and will make the change. But the try/catches are still necessary

**Comment by privateducky** [comment]
Oh definitely; still likely need try/catch statements for any unhandled cases (like this).

**Comment by mireaulf** [comment]
Closed by https://github.com/preludeorg/libraries/pull/217
