### ISSUE TITLE
Issue with token in Powershell

### ISSUE THREAD

**Issue by cipp-svbgroup** [preludeorg/libraries#964]
Hi. Just trying to run demo.ps1 to get an idea of how the Powershell SDK works.

I have extracted the token from my keychain.ini file and I am passing this to the demo.ps1 script, however when downloading the test I am getting the error:

Invoke-WebRequest : {"message":"User is not authorized to access this resource"}

Should I be using a different token, and if so, where do I generate this? If not, is there something I need to do to enable access via the API?

Many thanks in advance.

**Comment by packplusplus** [comment]
Hey cipp!

The "demo scripts" were a legacy experience, which are slated for removal (your ticket probably prompts us to finally remove them from the repo). You should probably play with an [ephemeral probe](https://docs.preludesecurity.com/docs/windows) instead. Both the demo scripts, and the ephemeral probes require an "endpoint token" not a "user token", which is why the values in your `keychain.ini` file don't work. If your cli isn't functioning, the "registration strings" you can generate on the platform site are different, and are used with the installers (registration strings are used by the installer to provision an endpoint token and put it in the right config file). 

Thanks for your interest in the product! We love feedback, so find us in [discord](https://discord.com/invite/NWURE99JzE) or hit our support email (support@preludesecurity.com) with whatever you have (positive or negative), but lets keep the issues page for code problems instead of configuration issues.
